### ISSUE TITLE
Extended MIDI capabilities? BTW great work!

### ISSUE THREAD

**Issue by ghost** [arthus701/midibigbutton#3]
Hi there, 
once again I' coming with a request about your project inspired by LMNC Big Button.
After all these months the MIDI-BIG-BUTTON worked great and your modificantions really upgrade the performance ability like replacing a shuffle knob with a speed knob - really useful idea!

But, not so long ago I've started ditching computer, because mine current one is not in so good condition. But, I still use MIDI devices - digital synths etc. So, to this project I've added a 5-pin din socket. I started learning about midi so I've made basic hardware implementations to have safe connection and I've soldered signal pin to the RX pin on ProMicro (the receiving one i guess) and change in your code one button from pin 0 to 1. 

My main question is : Can I have both usb and din inputs? (din input for clock only) or should I've buy a host? I'm guessing that this thing is possible in arduino environment, but neither i have skills in coding or money for usb-midi host.

Could I get some help from you?
Thanks.

**Comment by arthus701** [comment]
Hey, I'm really glad you like the project.

I never got to actually installing a midi-socket and thus cannot answer your question, sorry. If I got you right, you are suggesting to use a midi-input for clock and the USB as trigger output? Maybe the midi library can read both inputs and you could realize this via different midi channels, but I'd have to look further into the capabilities of both library and arduino to be sure.
Unfortunately I am quite busy with work these days and won't have the time to look at this for a couple of months...If you get any results or want to discuss anything more specific, feel free to reach out again.
Sorry I am not of more help, cheers and stay safe!

**Comment by ghost** [comment]
Hi, I understand that. You got my answer quite right. In short, Midi Big Button would keep all its characteristics, but I would add "midi clock input" (5 pin din). Well, when it comes to devices sending midi massages I got quite good with them, but when it comes to devices receiving I have no experience.

But, I'm quite stubborn guy, so probably I'm gonna make that  by myself. Also, I don't wanna be a dick so if my project will be successfull I post the code somwhere.

Maybe I would send it to you? Like via mail or something. With maybe some proof of working like pics or video of working device.

Stay safe and keep goin.

**Comment by arthus701** [comment]
We could also put it in a different branch of this repo or even merge it, depending on the changes you implement. Just get in touch once it's done :)
